root: true
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
rules:
  '@typescript-eslint/no-unused-vars': off
  '@typescript-eslint/no-var-requires': off
  '@typescript-eslint/no-inferrable-types': off
  '@typescript-eslint/no-empty-function': off
  no-var: off
  no-async-promise-executor: off
